### ISSUE TITLE
Settings to change square advance behavior

### ISSUE THREAD

**Issue by mdirolf** [mdirolf/crosshare#226]
Some relevant settings to implement:

- [x] Skip completed letters (default true)
- [x] Move to next word after completion (default true)
- [x] Perpendicular arrow key advances square (default false)

Copy any more good ones from puzzleme + NYT

**Comment by mdirolf** [comment]
The simplest way to do this would probably be to use `usePersistedBoolean` that we use for the `mute` toggle. This would store settings in local storage, so they'd be tied to user's browser rather than their account. I could see that being a feature (different settings for different devices) or a bug (different settings for different devices) 😂, so open to other opinions.

**Comment by glasser** [comment]
The preference I would love would be "don't move to next word after completion"; I often want to switch to the crossing clue rather than the next one.

(I also wish that arrow keys perpendicular to the current clue swapped direction without moving, but I can probably learn the current behavior eventually.)

**Comment by mdirolf** [comment]
Good suggestions @glasser - pulled those out into a checklist at the top of the issue

**Comment by mdirolf** [comment]
These have been added and will go out w/ the next deploy. @glasser I decided to change the default for perpendicular arrow keys to the way you wanted it - had another request for that behavior and realized that it matched the way the NYT app works.
