### ISSUE TITLE
Allowing Ñ on the grid for Spanish-language crosswords

### ISSUE THREAD

**Issue by davidmarchand** [mdirolf/crosshare#337]
Currently (both for constructing and solving), the grid doen't allow for the character **Ñ** to be entered in a cell, neither as a single letter or rebus. Only the 26 standard English letters are allowed. I've only tested on PC with Chrome.

I'm sure this is by design, and it's hard to accomodate multiple languages, but my proposed change is to add **Ñ** as a valid letter to be entered in the grid, to support Spanish crosswords. I'm not familiar with Crosshare's mobile keyboard, but the expected behavior on desktop would be having the character appear in a cell by pressing the Ñ key on my Spanish-language keyboard.

Spanish has a few diacritics that we tend to completely ignore in our crosswords, so adding Ñ (which isn't N with a diacritic but a separate letter) is the single change that would make all standard Spanish-language crossword-making supported.

**Comment by mdirolf** [comment]
It probably makes sense to just allow any unicode string as the contents of a cell.

There are likely lots of little things that would need to change throughout the codebase but the main one I can think of is the mobile keyboard. Perhaps the way to go is to use the phone's default keyboard when in rebus mode instead of the crosshare soft keyboard. So to enter a `Ñ` you'd hit "Rebus" and then enter the character as normal on your mobile phone's UX and then end the rebus. On desktop you would be able to just use your keyboard to enter it directly w/o going into rebus mode first.

Somewhat related to #312

**Comment by mdirolf** [comment]
I've decided to limit the scope of this to ñ rather than all unicode chars (and threw in '&' since I've had requests for it before). I added some dedicated keys to the mobile keyboard for those under the "More" tab. Also added support for pasting content into a grid cell so I could test Ñ easier since I don't have a key for it on my keyboard. Hoping to get a test build up for this soon
