### ISSUE TITLE
Some keyboard shortcuts are ignored

### ISSUE THREAD

**Issue by 1Computer1** [mdirolf/crosshare#353]
When crossword is active (in editor or not paused or not completed), certain keyboard inputs like F5 (refresh) or F11 (fullscreen) are ignored. Perhaps unrecognized inputs should just do their normal action?

**Comment by mdirolf** [comment]
Good call. We currently ignore keypresses w/ (non-shift) modifiers for that reason so that things like ctrl-r work. But I hadn't considered the function keys. Agreed it probably makes the most sense to have a list of keystrokes we do care about and then let everything else get handled by the browser as normal
